version: "3.5"

services:
  server:
    container_name: todo-caddy
    image: caddy:alpine
    depends_on:
      - backend
    volumes:
      - ./:/app
      - ./system/server/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    labels:
      traefik.enable: true
      traefik.http.routers.todo.rule: Host(`todo.anagraph.org`)
    ports:
      - 8000:80

  backend:
    container_name: todo-php
    build:
      context: .
      dockerfile: system/backend/Dockerfile
      args:
        PHP_VERSION: 7.1
        COMPOSER_VERSION: 1
    depends_on:
      - database
    volumes:
      - .:/app
      #Comment or uncomment below if you need to pass some custom instructions to php.ini (and put them in the /system/backend/php-custom.ini of course)
      - ./system/backend/php-custom.ini:/usr/local/etc/php/php.ini


  database:
    container_name: todo-mysql
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe
      MYSQL_DATABASE: todolist
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  caddy_data:
  caddy_config:
  mysql_data:

#networks:
#  default:
#    external: true
#    name: proxy