version: "3.5"

services:
  server:
    container_name: todo-caddy
    image: caddy:alpine
    depends_on:
      - backend
    volumes:
      - ./:/app
      - ./system/server/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    labels:
      traefik.enable: true
      traefik.http.routers.todo.rule: Host(`todo.anagraph.org`)
# Uncomment below to earn web access to the project without Traefik
    ports:
#      - 8000:80
      - 443:443

  backend:
    container_name: todo-php
    build:
      context: .
      dockerfile: system/backend/Dockerfile
      args:
        PHP_VERSION: 7.4
        COMPOSER_VERSION: 2
    depends_on:
      - database
    volumes:
      - .:/app
# Uncomment below if you need to pass some custom instructions to php.ini
      - ./system/backend/php-custom.ini:/usr/local/etc/php/php.ini

  database:
    container_name: todo-mysql
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ChangeMe
      MYSQL_DATABASE: todolist
    volumes:
      - mysql_data:/var/lib/mysql
# Uncomment below if you need to get direct access to your database
#    ports:
#      - 3306:3306

# Uncomment to set up blackfire agent (see also Dockerfile for php module)
  blackfire:
    container_name: todo-blackfire
    image: blackfire/blackfire
    env_file: .env.local
    ports: ["8707"]

volumes:
  caddy_data:
  caddy_config:
  mysql_data:

# Uncomment below to link with Traefik
#networks:
#  default:
#    external: true
#    name: proxy